name: release

on:
  push:
    branches:
      - master

jobs:
  release-github:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/create-github-app-token@v3
        id: auth
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          permission-contents: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          token: ${{ steps.auth.outputs.token }}

  release-test:
    needs: release-github
    if: needs.release-github.outputs.release-created == 'true'
    uses: ./.github/workflows/test.yml

  release-npm:
    needs: release-test
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
